-- MySQL Script generated by MySQL Workbench
-- Sun Sep 22 21:29:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BD_DEVRUMPER
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BD_DEVRUMPER` ;

-- -----------------------------------------------------
-- Schema BD_DEVRUMPER
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_DEVRUMPER` DEFAULT CHARACTER SET utf8 ;
USE `BD_DEVRUMPER` ;

-- -----------------------------------------------------
-- Table `BD_DEVRUMPER`.`TB_EMPRESAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_DEVRUMPER`.`TB_EMPRESAS` ;

CREATE TABLE IF NOT EXISTS `BD_DEVRUMPER`.`TB_EMPRESAS` (
  `EMP_ID` INT NOT NULL AUTO_INCREMENT,
  `EMP_EMPRESA` VARCHAR(100) NOT NULL,
  `EMP_CNPJ` INT(15) NOT NULL,
  `EMP_CNAE` INT(10) NOT NULL,
  `EMP_ENDERECO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`EMP_ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
